import { User } from './../user';
import { Component, OnInit, Output, EventEmitter } from '@angular/core';

@Component({
  selector: 'app-user-new',
  templateUrl: './user-new.component.html',
  styleUrls: ['./user-new.component.css']
})
export class UserNewComponent implements OnInit {
  newUser = new User();

  //component puts out new data that is generated by this event
  @Output() createNewUserEvent = new EventEmitter();

  constructor() { }

  ngOnInit() {
  }

  create(){
    //call server to save

    //new user event passes new user info to the create method
    this.createNewUserEvent.emit(this.newUser);
    this.newUser = new User(); //clears object by now pointing to a new user object (waiting for new input)
  }

}
